import Nav from "@/components/Nav"
import "./globals.css"

import { Poppins } from "next/font/google"

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={poppins.className}>
			<body className="bg-zinc-950 text-white min-h-screen">
				<Nav />
				{children}
			</body>
		</html>
	)
}
